name: Dockerfile-Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint the Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build and test image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: datanommer:latest

      - name: Test image
        run: >
          docker run -e ENVIRONMENT="" -e BROKER_URI="" -e TOPICS=""
          -e DB_HOST="" -e DB_NAME="" -e DB_USERNAME="" -e DB_PASSWORD=""
          datanommer:latest fedmsg-hub-3 --print-config
